"""Add new_column to your_table

Revision ID: e22a30f2cc60
Revises: 
Create Date: 2023-11-28 19:22:34.680041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e22a30f2cc60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament_schedule', schema=None) as batch_op:
        batch_op.drop_column('end_date')

    # ### end Alembic commands ###
