"""empty message

Revision ID: e38316af7032
Revises: e22a30f2cc60
Create Date: 2023-11-29 10:09:48.154262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e38316af7032'
down_revision = 'e22a30f2cc60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournament_schedule')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament_schedule',
    sa.Column('tournament_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('number_of_teams', sa.INTEGER(), nullable=False),
    sa.Column('team_id', sa.INTEGER(), nullable=False),
    sa.Column('team_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('start_date', sa.DATETIME(), nullable=True),
    sa.Column('end_date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('team_id')
    )
    # ### end Alembic commands ###
